In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a


array([1, 2, 3])

In [5]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)

In [6]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)],
              [(3, 2, 1), (4, 5, 6)]], dtype=float)

In [8]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [9]:
a,b,c

(array([1, 2, 3]),
 array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]),
 array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]],
 
        [[3. , 2. , 1. ],
         [4. , 5. , 6. ]]]))

In [10]:
a=np.zeros((3,4))

In [11]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
a=np.ones((2,3,4),dtype=np.int16)

In [16]:
a=np.arange(10,25,5)

In [17]:
a

array([10, 15, 20])

In [19]:
a=np.linspace(0,2,9)

In [20]:
a

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
a=np.full((2,2),7)

In [22]:
a

array([[7, 7],
       [7, 7]])

In [23]:
a=np.eye(2)

In [29]:
random=np.random.random((2,2))

In [31]:
a,random

(array([[1., 0.],
        [0., 1.]]),
 array([[0.17170239, 0.35313546],
        [0.65306244, 0.76313679]]))

In [33]:
print("Array a -> shape:", a.shape, " ndim:", a.ndim, " size:", a.size)
print("Array b -> shape:", b.shape, " ndim:", b.ndim, " size:", b.size)
print("Array c -> shape:", c.shape, " ndim:", c.ndim, " size:", c.size)

Array a -> shape: (2, 2)  ndim: 2  size: 4
Array b -> shape: (2, 2)  ndim: 2  size: 4
Array c -> shape: (2, 2, 3)  ndim: 3  size: 12


In [41]:
print("Data type of b:", b.dtype)
print("Data type name:", b.dtype.name)
b_int = b.astype(int)
print("b converted to integer:\n", b_int)

Data type of b: float64
Data type name: float64
b converted to integer:
 [[0 0]
 [0 0]]


In [42]:
a+b

array([[1.78758759, 0.99754253],
       [0.69293455, 1.6439086 ]])

In [43]:
a-b

array([[ 0.21241241, -0.99754253],
       [-0.69293455,  0.3560914 ]])

In [44]:
a*b

array([[0.78758759, 0.        ],
       [0.        , 0.6439086 ]])

In [45]:
a/b

array([[1.26970004, 0.        ],
       [0.        , 1.55301543]])

In [46]:
x=np.sqrt(b)

In [47]:
x

array([[0.88746132, 0.99877051],
       [0.8324269 , 0.80243916]])

In [50]:
d=np.array([5,6,7])
np.sum(d)

np.int64(18)

In [51]:
np.min(d)

np.int64(5)

In [52]:
np.max(d)

np.int64(7)

In [53]:
np.cumsum(d)

array([ 5, 11, 18])

In [54]:
np.mean(d)

np.float64(6.0)

In [55]:
np.median(d)

np.float64(6.0)

In [56]:
np.std(d)

np.float64(0.816496580927726)